= Invalid execution results =
| ----------------- |
|     Thread 1      |
| ----------------- |
| operation(): void |
| ----------------- |

The following interleaving leads to the error:
| ----------- |
|  Thread 1   |
| ----------- |
| operation() |
| ----------- |

Detailed trace:
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|                                                                              Thread 1                                                                              |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| operation()                                                                                                                                                        |
|   escape = "START" at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:32)            |
|   run() at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:33)                       |
|     setEscape("BEFORE BLOCK") at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:42) |
|       escape = "BEFORE BLOCK" at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:20) |
|     run$Lambda() at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:44)              |
|       escape = "IN LAMBDA" at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:34)    |
|   run() at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:46)                       |
|     run$Lambda() at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:46)              |
|       escape = "AFTER LAMBDA" at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:36) |
|     setEscape("AFTER BLOCK") at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:46)  |
|       escape = "AFTER BLOCK" at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:20)  |
|   escape = "END" at InlineLambdaConditionalNotTakenFullReturnFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnFinallyTest.kt:38)              |
|   result: void                                                                                                                                                     |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
