= Invalid execution results =
| ----------------- |
|     Thread 1      |
| ----------------- |
| operation(): void |
| ----------------- |

The following interleaving leads to the error:
| ----------- |
|  Thread 1   |
| ----------- |
| operation() |
| ----------- |

Detailed trace:
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|                                                                                    Thread 1                                                                                    |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| operation()                                                                                                                                                                    |
|   returnInt(): -5 at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:32)               |
|     escape = "START" at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:36)            |
|     run() at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:37)                       |
|       setEscape("BEFORE BLOCK") at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:48) |
|         escape = "BEFORE BLOCK" at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:20) |
|       run$Lambda() at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:50)              |
|         escape = "IN LAMBDA" at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:38)    |
|     run() at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:52)                       |
|       run$Lambda() at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:52)              |
|         escape = "AFTER LAMBDA" at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:40) |
|     setEscape("AFTER BLOCK") at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:52)    |
|       escape = "AFTER BLOCK" at InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.<unknown method>(InlineLambdaConditionalNotTakenFullReturnValueFinallyTest.kt:20)    |
|   result: void                                                                                                                                                                 |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
