= Invalid execution results =
| ----------------- |
|     Thread 1      |
| ----------------- |
| operation(): void |
| ----------------- |

The following interleaving leads to the error:
| ----------- |
|  Thread 1   |
| ----------- |
| operation() |
| ----------- |

Detailed trace:
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|                                                                                              Thread 1                                                                                               |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| operation()                                                                                                                                                                                         |
|   escape = "START" at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:33)                                                                  |
|   run(): threw RuntimeException at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:35)                                                     |
|     setEscape("BEFORE BLOCK") at InlineLambdaConditionalTaken2ndLevelThrowTest.run(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:51)                                                             |
|       escape = "BEFORE BLOCK" at InlineLambdaConditionalTaken2ndLevelThrowTest.setEscape(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:21)                                                       |
|     run$Lambda(): threw RuntimeException at InlineLambdaConditionalTaken2ndLevelThrowTest.run(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:52)                                                  |
|       escape = "IN LAMBDA 1" at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:36)                                                        |
|       InlineLambdaConditionalTaken2ndLevelThrowTest#1.run(): threw RuntimeException at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:37) |
|         setEscape("BEFORE BLOCK") at InlineLambdaConditionalTaken2ndLevelThrowTest.run(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:51)                                                         |
|           escape = "BEFORE BLOCK" at InlineLambdaConditionalTaken2ndLevelThrowTest.setEscape(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:21)                                                   |
|         run$Lambda(): threw RuntimeException at InlineLambdaConditionalTaken2ndLevelThrowTest.run(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:52)                                              |
|           escape = "IN LAMBDA 2" at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:38)                                                    |
|   escape = "CATCH" at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:45)                                                                  |
|   escape = "END" at InlineLambdaConditionalTaken2ndLevelThrowTest.operation(InlineLambdaConditionalTaken2ndLevelThrowTest.kt:47)                                                                    |
|   result: void                                                                                                                                                                                      |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
