= The execution failed with an unexpected exception =
| ------------------------------ |
|     Thread 1     |  Thread 2   |
| ------------------------------ |
| incrementTwice() | operation() |
| ------------------------------ |

java.lang.RuntimeException: It seems that you use Java 9+ and the code uses Unsafe or similar constructions that are not accessible from unnamed modules.
Please add the following lines to your test running configuration:
--add-opens java.base/jdk.internal.misc=ALL-UNNAMED
--add-exports java.base/jdk.internal.util=ALL-UNNAMED
--add-exports java.base/sun.security.action=ALL-UNNAMED
	at org.jetbrains.kotlinx.lincheck.UtilsKt.wrapInvalidAccessFromUnnamedModuleExceptionWithDescription(Utils.kt:338)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.onFailure(ManagedStrategy.kt:330)
	at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategyRunner.onFailure(ManagedStrategy.kt:1105)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution.failOnExceptionIsUnexpected(TestThreadExecution.java:59)
	at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution226.run(Unknown Source)
	at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.testThreadRunnable$lambda-8(FixedActiveThreadsExecutor.kt:149)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessException: module java.base does not "opens java.io" to unnamed module
	at org.jetbrains.kotlinx.lincheck_test.representation.IllegalModuleAccessOutputMessageTest$operation$1.invoke(IllegalModuleAccessOutputMessageTest.kt:39)
	at org.jetbrains.kotlinx.lincheck_test.representation.IllegalModuleAccessOutputMessageTest$operation$1.invoke(IllegalModuleAccessOutputMessageTest.kt:39)
	at org.jetbrains.kotlinx.lincheck.util.InternalLincheckExceptionEmulator.throwException(InternalLincheckExceptionEmulator.kt:24)
	at org.jetbrains.kotlinx.lincheck_test.representation.IllegalModuleAccessOutputMessageTest.operation(IllegalModuleAccessOutputMessageTest.kt:39)
	... 3 more


The following interleaving leads to the error:
| ----------------------------------------------------------------------------------------------------------------------------------------------- |
|                                                             Thread 1                                                              |  Thread 2   |
| ----------------------------------------------------------------------------------------------------------------------------------------------- |
| incrementTwice()                                                                                                                  |             |
|   counter.incrementAndGet(): 1 at IllegalModuleAccessOutputMessageTest.incrementTwice(IllegalModuleAccessOutputMessageTest.kt:32) |             |
|   switch                                                                                                                          |             |
|                                                                                                                                   | operation() |
| ----------------------------------------------------------------------------------------------------------------------------------------------- |

Detailed trace:
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|                                                             Thread 1                                                              |                                                    Thread 2                                                     |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| incrementTwice()                                                                                                                  |                                                                                                                 |
|   counter.incrementAndGet(): 1 at IllegalModuleAccessOutputMessageTest.incrementTwice(IllegalModuleAccessOutputMessageTest.kt:32) |                                                                                                                 |
|   switch                                                                                                                          |                                                                                                                 |
|                                                                                                                                   | operation()                                                                                                     |
|                                                                                                                                   |   counter.READ: 1 at IllegalModuleAccessOutputMessageTest.operation(IllegalModuleAccessOutputMessageTest.kt:38) |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
